name: Rust

on:
  workflow_dispatch: null
  push:
    branches: [ "main" ]
    paths:
      - rust/**
  # pull_request:
  #  branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
defaults:
  run:
    shell: bash
jobs:
  build-print-hello-world:
    defaults:
      run:
        working-directory: rust/wasi/print-hello-world
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build for WASM
      run: cargo build --target wasm32-wasi
    #- name: Run tests
   #   run: cargo test --verbose
