name: Rust

on:
  push:
    branches: [ "main" ]
    paths:
      - rust/**
  # pull_request:
  #  branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  print-hello-world:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: cd wasi/print-hello-world
    - name: Build
      run: cargo build --target wasm32-wasi
    #- name: Run tests
   #   run: cargo test --verbose
