name: Rust

on:
  workflow_dispatch: null
  push:
    branches: [ "main" ]
    paths:
      - rust/**
  # pull_request:
  #  branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
defaults:
  run:
    shell: bash
jobs:
  build-print-hello-world:
    defaults:
      run:
        working-directory: rust/wasi/print-hello-world
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install the wasm32-wasi target
      run: rustup target add wasm32-wasi
    - name: Install binaryen
      run: |
          sudo apt update
          sudo apt -y install binaryen
    - name: Build WASM in release profile
      run: cargo build --target wasm32-wasi --release
    - name: optimize the resulting wasm file for size
      run:  wasm-opt -Os -o target/wasm32-wasi/release/rust-print-hello-world.wasm target/wasm32-wasi/release/print-hello-world.wasm
      
    - uses: actions/upload-artifact@v3
      with:
        name: rust builds
        path: |
          target/wasm32-wasi/release/*.wasm
          # !dist/**/*.md
    #- name: Run tests
   #   run: cargo test --verbose
